### ISSUE TITLE
`repo.xml` has two `creator` entries

### ISSUE THREAD

**Issue by michaelherger** [Foxenfurter/SqueezeDSP#8]
https://raw.githubusercontent.com/Foxenfurter/SqueezeBoxEQ/main/repo.xml has to `creator` entries for SqueezeDSP. But I didn't find that file in your repo?!?

**Comment by Foxenfurter** [comment]
Yes, I was using a single Repo entry for 2 separate plugins. I thought that this would simplify things for updates etc. Let me know if this is wrong.

**Comment by michaelherger** [comment]
That's no problem: I have a dozen or more in one file. But the entry for SqueezeDSP alone has two creator entries. That's causing an issue in some of the scripts I have to integrate them with LMS' plugin manager.

**Comment by Foxenfurter** [comment]
I can see what you are referring to now, I have removed the superfluous creator entry.
